NUMBER_OF_PEERS = 50
Z0 = 0.3  # network z0 is slow
Z1 = 0.9  # cpu z1 is slow
NUMBER_OF_TRANSACTIONS = 20*NUMBER_OF_PEERS

RATE_PARAMETER = 0.1
INITIAL_COINS = 100
EVENT_QUEUE_TIMEOUT = 5
BLOCK_GEN_TRXN_THRESHOLD = 10
INITIAL_AVG_INTERVAL_TIME = 1/RATE_PARAMETER  # avg block interval time
