SAVE_RESULTS = False
#
NUMBER_OF_PEERS = 20
Z0 = 0.3  # network z0 is slow
# Z1 = 0.2  # cpu z1 is slow
NUMBER_OF_TRANSACTIONS_PER_PEER = 20
NUMBER_OF_TRANSACTIONS = NUMBER_OF_TRANSACTIONS_PER_PEER * NUMBER_OF_PEERS

Z1 = 0.3
Z2 = 0.4

# mean of exponential time interval bw transactions (ms)
INITIAL_COINS = 1000
EVENT_QUEUE_TIMEOUT = 5
BLOCK_TXNS_MAX_THRESHHOLD = 20  # 1020
BLOCK_TXNS_MIN_THRESHHOLD = 1
AVG_TXN_INTERVAL_TIME = 1000
AVG_BLOCK_MINING_TIME = 100  # avg block interval time (ms)

# sim stop conditions
MAX_NUM_BLOCKS = (
    NUMBER_OF_TRANSACTIONS - NUMBER_OF_TRANSACTIONS_PER_PEER
) / BLOCK_TXNS_MAX_THRESHHOLD
